```{r}
library(checkpoint)
checkpoint("2022-01-01")
library(magrittr)
library(dplyr)
library(tidyr)
library(readxl)
library(readr)
library(ggplot2)
setwd("MM_2022W1")
```

```{r}
df <-
  "MM_2022W1 - cereal.xlsx" %>%
  read_excel() %>%
  pivot_longer(-c(name, Manufacturer, type), names_to = "feature") %>%
  mutate(featureAbbr = case_when(feature == "calories per serving" ~ "Calories",
                                 feature == "grams of protein" ~ "Protein",
                                 feature == "grams of fat" ~ "Fat",
                                 feature == "milligrams of sodium" ~ "Sodium",
                                 feature == "grams of dietary fiber" ~ "Fiber",
                                 feature == "grams of complex carbohydrates" ~ "Carbohydrates",
                                 feature == "grams of sugars" ~ "Sugars",
                                 feature == "milligrams of potassium" ~ "Potassium",
                                 feature == "vitamins and minerals (% of FDA recommendation)" ~ "Vitamins/Minerals",
                                 feature == "Display shelf" ~ "Shelf",
                                 feature == "Weight in ounces per one serving" ~ "Ounces",
                                 feature == "Number of cups in one serving" ~ "Cups",
                                 feature == "Rating of cereal" ~ "**Rating**"))
```

```{r}
df %>%
  inner_join(., ., by = c("name", "Manufacturer", "type")) %>%
  write_csv("MM_2022W1_long.csv")
```

```{r}
G <-
  df %>%
  select(-c(Manufacturer, type, feature)) %>%
  inner_join(., ., by = "name") %>%
  filter(featureAbbr.x > featureAbbr.y) %>%
  ggplot(aes(x = value.x, y = value.y)) +
    geom_point(alpha = 0.25) +
    geom_smooth(method = "lm") +
    scale_x_continuous("") +
    scale_y_continuous("") +
    facet_grid(featureAbbr.y ~ featureAbbr.x, scales = "free") +
    theme_bw() +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank())
ggsave("MM_2022W1_matrixPlot.png", width = 4000, height = 4000, units = "px")
```

```{r}
G <-
  df %>%
  select(-c(Manufacturer, type, feature)) %>%
  inner_join(., ., by = "name") %>%
  filter(featureAbbr.x > featureAbbr.y) %>%
  group_by(featureAbbr.x, featureAbbr.y) %>%
  summarize(r = cor(value.x, value.y)) %>%
  ungroup() %>%
  ggplot(aes(x = featureAbbr.x, y = featureAbbr.y, fill = r)) +
    geom_tile(color = "#f5f5f5") +
    scale_fill_gradient2(low = "#ec8902",
                         high = "#005595",
                         mid = "#f2f2f2",
                         midpoint = 0,
                         limit = c(-1, 1),
                         space = "Lab",
                         name = "Correlation") +
    scale_y_discrete(limits = rev) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.grid.major = element_blank()) +
    coord_fixed()
ggsave("MM_2022W1_corrHeatmap.png", width = 1500, height = 1500, units = "px")
```


# Predictive model

* Don't split into training/testing samples. Entire sample will be treated as a training sample.
* Only interesting in variable importance.

```{r}
library(caret)
df <-
  read_excel(path = f) %>%
  select(-c(name))
model <- function (data, method) {
  require(caret)
  F <- formula(`Rating of cereal` ~ .)
  ctrl <- trainControl(method = "cv",
                       number = 10,
                       savePredictions = TRUE,
                       allowParallel = FALSE)
  train(F,
        data = data,
        method = method,
        trControl = ctrl,
        metric = "MAE",
        maximize = FALSE)
}
```

eXtreme Gradient Boosting

```{r}
model(df, "xgbTree") %>% varImp()
```

Random Forest

```{r}
model(df, "cforest") %>% varImp()
```

Conditional Inference Random Forest

```{r}
model(df, "rf") %>% varImp()
```

glmnet

```{r}
model(df, "glmnet") %>% varImp()
```
